#!/bin/sh

# host is called Wagner because that's the name
# of my neighbour who donated the computer case
[ "$(hostname)" = "wagner" ] || exit 0

# main host is called Antec: that's the brand off the case

# is it still up ?
ping -qc 1 antec > /dev/null || exit 0
rsync -rlpgotDixv -e ssh melanie@antec:/home/mp3 /home/ --delete --inplace

# is it still up ?
ping -qc 1 antec > /dev/null || exit 0
rsync -rlpgotDixv -e ssh melanie@antec:/home/photos /home/ --delete --inplace
