#!/bin/sh
set -e

# remove obsolete conf files,
# these jobs are now stored in /etc/site/
rm -f /etc/cron.daily/0wait
rm -f /etc/cron.daily/zz_clean
rm -f /etc/cron.daily/zz_desktop_notification

if [ -e /etc/apt/sources.list.d/getdeb.list ]
then
    new="deb http://archive.getdeb.net/ubuntu wily-getdeb games"
    old=$(cat /etc/apt/sources.list.d/getdeb.list)
    if [ "$new" != "$old" ]
    then
        echo "$new" > /etc/apt/sources.list.d/getdeb.list
    fi
fi

if [ "$(hostname)" = "wagner" ]
then
	cp /etc/site/parenting /etc/cron.d/
fi

#DEBHELPER#
